workflows:
  reports-ui:
    name: Reports UI Deployment

    environment:
      node: 21
      npm: 10
      groups:
        - aws_credentials
        - build_variables

    scripts:
      - name: Install Dependencies
        script: |
          npm i

      - name: Build Web App
        script: |
          npm run build:app

      - name: Upload Build to S3
        script: |
          BUCKET=""

          case "$ENVIRONMENT" in
            "UAT")
              BUCKET="reportsuiuat"
              ;;
            "DEMO")
              BUCKET="reportsuidemo"
              ;;
            "PROD")
              BUCKET="reportsui"
              ;;
            *)
              echo "Unknown environment: $ENVIRONMENT"
              exit 1
          esac

          aws s3 sync dist-app/ s3://${BUCKET}/